apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: rsh
spec:
  version: "v0.2.0"
  homepage: https://github.com/worldline/kubectl-rsh
  shortDescription: "Execute a command or open a shell session to a container in a pod"
  description: |
    Execute a command or opens a shell session to a container in a pod, just like "oc rsh"
  platforms:
  - uri: https://github.com/worldline/kubectl-rsh/releases/download/0.2.0/kubectl-rsh_0.2.0_x86_64-unknown-linux-gnu.tar.gz
    sha256: 14c8cb362100d62b6df813e3a67cb5e930bf0e5fa039616f97225691c99cf4ab
    bin: kubectl-rsh
    files:
    - from: "*"
      to: "."
    selector:
      matchLabels:
        os: linux
        arch: amd64
